import { Job } from './types';

export const INITIAL_JOBS: Omit<Job, 'id'>[] = [
  {
    title: 'Senior Full Stack Engineer',
    company: 'Vercel',
    logo_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop&crop=faces',
    location: 'San Francisco, CA',
    is_remote: true,
    job_type: 'Full-time',
    experience_level: 'Senior',
    salary_min: 165000,
    salary_max: 215000,
    currency: 'USD',
    department: 'Engineering',
    description: 'We are seeking a Senior Full Stack Engineer to lead architecture and development across modern web frontend and scalable edge microservices. You will work closely with design and infrastructure teams to deliver high-performance developer experiences.',
    requirements: [
      '5+ years of experience with React, Next.js, and TypeScript',
      'Strong knowledge of Node.js, RESTful APIs, and GraphQL',
      'Experience with SQL/NoSQL databases (PostgreSQL, Redis)',
      'Familiarity with serverless architectures and edge computing',
      'Track record of building and maintaining production web applications at scale'
    ],
    responsibilities: [
      'Architect, develop, and deploy full-stack web applications and APIs',
      'Collaborate with product designers and engineering leadership',
      'Conduct rigorous code reviews and mentor junior and mid-level engineers',
      'Improve performance, reliability, and security of core platforms'
    ],
    skills: ['React', 'Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'GraphQL', 'AWS', 'Tailwind CSS', 'Docker'],
    posted_at: '2026-09-02T10:00:00Z',
    apply_url: 'https://vercel.com/careers',
  },
  {
    title: 'Full Stack Developer',
    company: 'Stripe',
    logo_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&h=128&fit=crop&crop=faces',
    location: 'Seattle, WA',
    is_remote: true,
    job_type: 'Full-time',
    experience_level: 'Mid',
    salary_min: 140000,
    salary_max: 180000,
    currency: 'USD',
    department: 'Engineering',
    description: 'Join the Stripe Payments experience team building seamless checkout flows and merchant portals used by millions of businesses worldwide. You will craft intuitive UIs backed by high-throughput transactional services.',
    requirements: [
      '3+ years of professional full-stack development experience',
      'Proficiency in JavaScript, TypeScript, React, and Ruby or Go or Node.js',
      'Experience building robust, accessible, and responsive user interfaces',
      'Solid understanding of database systems, caching, and distributed systems'
    ],
    responsibilities: [
      'Build merchant and consumer dashboard experiences',
      'Design reliable APIs that handle millions of requests per second',
      'Participate in on-call rotation and production triage',
      'Partner with product managers to clarify specs and deliver features'
    ],
    skills: ['TypeScript', 'React', 'Node.js', 'Go', 'Ruby', 'PostgreSQL', 'Redis', 'REST APIs', 'System Design'],
    posted_at: '2026-09-01T14:30:00Z',
    apply_url: 'https://stripe.com/jobs',
  },
  {
    title: 'Frontend Engineer',
    company: 'Linear',
    logo_url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=128&h=128&fit=crop&crop=faces',
    location: 'Remote',
    is_remote: true,
    job_type: 'Full-time',
    experience_level: 'Mid',
    salary_min: 135000,
    salary_max: 175000,
    currency: 'USD',
    department: 'Product Engineering',
    description: 'Linear is looking for a thoughtful Frontend Engineer passionate about speed, fluidity, and craft. You will be building desktop-grade web applications with ultra-responsive keyboard shortcuts and real-time syncing.',
    requirements: [
      'Demonstrated expertise in modern React, TypeScript, and state management',
      'Deep understanding of browser rendering, WebSockets, and performance profiling',
      'Passion for micro-interactions, keyboard navigation, and design fidelity',
      'Strong eye for aesthetics and user empathy'
    ],
    responsibilities: [
      'Build real-time collaborative workspace features',
      'Optimize client-side rendering and optimistic UI updates',
      'Maintain and expand our comprehensive design system',
      'Collaborate directly with designers and users on customer feedback'
    ],
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'WebSockets', 'State Management', 'Figma', 'UI/UX Design', 'Performance'],
    posted_at: '2026-09-03T09:15:00Z',
    apply_url: 'https://linear.app/careers',
  },
  {
    title: 'Senior Backend Engineer',
    company: 'Datadog',
    logo_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=128&h=128&fit=crop&crop=faces',
    location: 'New York, NY',
    is_remote: false,
    job_type: 'Full-time',
    experience_level: 'Senior',
    salary_min: 175000,
    salary_max: 230000,
    currency: 'USD',
    department: 'Platform Engineering',
    description: 'Datadog is looking for a Senior Backend Engineer to join our telemetry processing team. You will build distributed systems that ingest and analyze petabytes of metrics, logs, and traces per day.',
    requirements: [
      '5+ years building backend distributed systems at scale',
      'Deep expertise in Go, Python, or Java/C++',
      'Experience with Kafka, Kubernetes, and distributed storage engines',
      'Thorough understanding of network protocols, concurrency, and Linux internals'
    ],
    responsibilities: [
      'Design resilient ingestion pipelines processing billions of events',
      'Profile memory and CPU utilization to optimize throughput',
      'Establish architectural standards across multiple platform teams',
      'Troubleshoot complex production issues in high-scale environments'
    ],
    skills: ['Go', 'Python', 'Kubernetes', 'Kafka', 'Docker', 'PostgreSQL', 'Microservices', 'Distributed Systems', 'Linux'],
    posted_at: '2026-08-30T11:00:00Z',
    apply_url: 'https://careers.datadoghq.com',
  },
  {
    title: 'Machine Learning Engineer',
    company: 'OpenAI',
    logo_url: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=128&h=128&fit=crop&crop=faces',
    location: 'San Francisco, CA',
    is_remote: false,
    job_type: 'Full-time',
    experience_level: 'Senior',
    salary_min: 210000,
    salary_max: 290000,
    currency: 'USD',
    department: 'Applied AI',
    description: 'We are looking for a Machine Learning Engineer to build and fine-tune large language models and multi-modal systems, deploying models to low-latency inference pipelines serving millions of developers.',
    requirements: [
      'MS or PhD in Computer Science, Machine Learning, or equivalent industry experience',
      'Hands-on expertise with PyTorch, Transformers, and LLM fine-tuning techniques (LoRA, RLHF)',
      'Experience scaling distributed model training across multi-node GPU clusters',
      'Strong software engineering fundamentals in Python and C++'
    ],
    responsibilities: [
      'Train, evaluate, and optimize cutting-edge generative models',
      'Develop evaluation harnesses and benchmark suites',
      'Scale inference infrastructure with quantization and kernel optimization',
      'Collaborate with safety and research teams on model alignment'
    ],
    skills: ['Python', 'PyTorch', 'Machine Learning', 'Deep Learning', 'LLMs', 'C++', 'CUDA', 'Docker', 'NLP'],
    posted_at: '2026-09-02T16:45:00Z',
    apply_url: 'https://openai.com/careers',
  },
  {
    title: 'Product Manager - Core Experience',
    company: 'Figma',
    logo_url: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=128&h=128&fit=crop&crop=faces',
    location: 'San Francisco, CA',
    is_remote: true,
    job_type: 'Full-time',
    experience_level: 'Senior',
    salary_min: 170000,
    salary_max: 220000,
    currency: 'USD',
    department: 'Product',
    description: 'Figma is looking for a Senior Product Manager to lead product strategy for collaborative canvas tooling. You will define the roadmap for features used by millions of designers and product teams globally.',
    requirements: [
      '4+ years of product management experience shipping developer or design tools',
      'Strong user empathy and ability to distill complex technical challenges into clear roadmaps',
      'Proven track record of data-driven decision making and experimentation',
      'Superb communication and cross-functional leadership skills'
    ],
    responsibilities: [
      'Define product vision, strategy, and metrics for canvas features',
      'Collaborate with engineering and design leads on product delivery',
      'Engage with enterprise customers to understand workflows and pain points',
      'Drive feature launches, positioning, and go-to-market execution'
    ],
    skills: ['Product Management', 'Figma', 'Agile', 'Scrum', 'User Research', 'Data Analytics', 'Roadmapping', 'System Design'],
    posted_at: '2026-08-31T15:20:00Z',
    apply_url: 'https://www.figma.com/careers',
  },
  {
    title: 'Lead UI/UX Product Designer',
    company: 'Airbnb',
    logo_url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=128&h=128&fit=crop&crop=faces',
    location: 'Remote',
    is_remote: true,
    job_type: 'Full-time',
    experience_level: 'Lead',
    salary_min: 185000,
    salary_max: 240000,
    currency: 'USD',
    department: 'Design',
    description: 'Lead design initiatives for the host and guest trip planning experience. You will craft delightful, intuitive, and accessible user journeys across mobile apps and the responsive web.',
    requirements: [
      '7+ years of experience in product design, interaction design, and design systems',
      'An outstanding portfolio demonstrating end-to-end design craft and systems thinking',
      'Mastery of Figma, rapid prototyping, and interaction design tools',
      'Experience leading design reviews and coaching junior designers'
    ],
    responsibilities: [
      'Direct visual and interaction design for consumer travel flows',
      'Conduct generative user research and prototype user testing',
      'Contribute to our global design system standards and accessibility guidelines',
      'Partner with engineering on pixel-perfect implementation'
    ],
    skills: ['UI/UX Design', 'Figma', 'Wireframing', 'User Research', 'Design Systems', 'Prototyping', 'Product Management'],
    posted_at: '2026-09-03T11:45:00Z',
    apply_url: 'https://careers.airbnb.com',
  },
  {
    title: 'DevOps & Cloud Infrastructure Engineer',
    company: 'Brex',
    logo_url: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=128&h=128&fit=crop&crop=faces',
    location: 'New York, NY',
    is_remote: true,
    job_type: 'Full-time',
    experience_level: 'Mid',
    salary_min: 145000,
    salary_max: 185000,
    currency: 'USD',
    department: 'Infrastructure',
    description: 'Help manage and scale Brex cloud platform infrastructure across multiple AWS regions with high availability, strict financial security, and automated CI/CD pipelines.',
    requirements: [
      '3+ years managing production infrastructure on AWS or GCP',
      'Strong experience with Terraform, Kubernetes, and Helm',
      'Solid scripting skills in Python, Bash, or Go',
      'Experience with SOC2, security compliance, and zero-trust networks'
    ],
    responsibilities: [
      'Maintain automated multi-region Kubernetes clusters',
      'Implement Terraform modules for self-service developer environments',
      'Enhance monitoring, alerting, and automated incident recovery',
      'Collaborate with security engineers on intrusion prevention and audits'
    ],
    skills: ['AWS', 'Kubernetes', 'Terraform', 'Docker', 'CI/CD', 'GitHub Actions', 'Python', 'Linux', 'Bash'],
    posted_at: '2026-09-02T13:10:00Z',
    apply_url: 'https://www.brex.com/careers',
  },
  {
    title: 'Data Engineer - Analytics & Pipelines',
    company: 'Spotify',
    logo_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=128&h=128&fit=crop&crop=faces',
    location: 'New York, NY',
    is_remote: true,
    job_type: 'Full-time',
    experience_level: 'Mid',
    salary_min: 135000,
    salary_max: 175000,
    currency: 'USD',
    department: 'Data & Analytics',
    description: 'Build high-throughput data processing pipelines powering music recommendation algorithms, royalties calculation, and executive business intelligence dashboards.',
    requirements: [
      '3+ years of experience with distributed data processing (Spark, Flink, or Beam)',
      'Expert SQL skills and advanced proficiency in Python or Scala/Java',
      'Hands-on experience with data warehouses (BigQuery, Snowflake, or Redshift)',
      'Familiarity with data orchestration tools such as Airflow or Dagster'
    ],
    responsibilities: [
      'Build scalable batch and real-time streaming data pipelines',
      'Ensure data quality, integrity, and SLA compliance across core datasets',
      'Partner with data scientists and analysts to curate analysis-ready tables',
      'Optimize database queries and cloud warehouse compute costs'
    ],
    skills: ['Python', 'SQL', 'PostgreSQL', 'AWS', 'GCP', 'Data Analytics', 'ETL', 'Docker', 'Apache Spark'],
    posted_at: '2026-08-29T08:00:00Z',
    apply_url: 'https://www.lifeatspotify.com/jobs',
  },
  {
    title: 'Junior Software Engineer (Web & Mobile)',
    company: 'Discord',
    logo_url: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=128&h=128&fit=crop&crop=faces',
    location: 'San Francisco, CA',
    is_remote: false,
    job_type: 'Full-time',
    experience_level: 'Entry',
    salary_min: 105000,
    salary_max: 130000,
    currency: 'USD',
    department: 'Engineering',
    description: 'An exciting opportunity for early-career engineers to join Discord. You will work on real-time voice, video, and text communication features enjoyed by hundreds of millions of users.',
    requirements: [
      'B.S. in Computer Science, Software Engineering, or equivalent practical experience',
      'Solid grounding in JavaScript, TypeScript, HTML, and CSS',
      'Understanding of React, Git, and RESTful web concepts',
      'Eagerness to learn, collaborate, and receive code mentorship'
    ],
    responsibilities: [
      'Implement feature improvements and bug fixes across Discord clients',
      'Write clean, well-tested TypeScript and React components',
      'Participate in team planning, standups, and retrospective meetings',
      'Collaborate with senior engineers to expand technical skills'
    ],
    skills: ['JavaScript', 'TypeScript', 'React', 'HTML', 'CSS', 'Git', 'REST APIs', 'Problem Solving'],
    posted_at: '2026-09-03T13:00:00Z',
    apply_url: 'https://discord.com/careers',
  },
  {
    title: 'iOS Mobile Developer',
    company: 'Apple',
    logo_url: 'https://images.unsplash.com/photo-1510519138171-c73d9e830f36?w=128&h=128&fit=crop&crop=faces',
    location: 'Cupertino, CA',
    is_remote: false,
    job_type: 'Full-time',
    experience_level: 'Senior',
    salary_min: 170000,
    salary_max: 225000,
    currency: 'USD',
    department: 'iOS Engineering',
    description: 'Build native iOS applications leveraging Swift, SwiftUI, and modern Apple frameworks. You will craft responsive, battery-efficient, and accessible consumer applications.',
    requirements: [
      '5+ years developing native iOS applications with Swift and Objective-C',
      'Strong experience with SwiftUI, Combine, and UIKit architecture',
      'Deep knowledge of memory management, Core Data, and Instruments profiling',
      'Published applications on the App Store with high ratings'
    ],
    responsibilities: [
      'Develop native mobile features with smooth animations and intuitive UX',
      'Ensure high code coverage through automated unit and UI testing',
      'Optimize network utilization, memory footprints, and frame rates',
      'Guide technical design documents and architectural improvements'
    ],
    skills: ['Swift', 'iOS', 'SwiftUI', 'REST APIs', 'Git', 'System Design', 'Mobile Development'],
    posted_at: '2026-08-28T16:00:00Z',
    apply_url: 'https://jobs.apple.com',
  },
  {
    title: 'Cybersecurity Operations Analyst',
    company: 'CrowdStrike',
    logo_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=128&h=128&fit=crop&crop=faces',
    location: 'Austin, TX',
    is_remote: true,
    job_type: 'Full-time',
    experience_level: 'Mid',
    salary_min: 125000,
    salary_max: 160000,
    currency: 'USD',
    department: 'Security Operations',
    description: 'Monitor enterprise threat landscapes, investigate security incidents, and develop automated detection rules to protect infrastructure against emerging cyber adversaries.',
    requirements: [
      '3+ years in security operations, threat hunting, or incident response',
      'Working knowledge of SIEM tools, EDR solutions, and network forensics',
      'Proficiency in Python or Bash for automation and log analysis',
      'Understanding of MITRE ATT&CK framework and vulnerability management'
    ],
    responsibilities: [
      'Investigate security alerts, anomalous activities, and indicators of compromise',
      'Write automated detection playbooks in Python',
      'Perform root cause analyses on security incidents and draft post-mortems',
      'Conduct regular vulnerability assessments and coordinate patching'
    ],
    skills: ['Python', 'Linux', 'Bash', 'Security', 'SIEM', 'Threat Analysis', 'AWS'],
    posted_at: '2026-08-27T09:40:00Z',
    apply_url: 'https://www.crowdstrike.com/careers',
  },
  {
    title: 'React Native Developer (Contract)',
    company: 'Coinbase',
    logo_url: 'https://images.unsplash.com/photo-1621416894569-0f39ed31d247?w=128&h=128&fit=crop&crop=faces',
    location: 'Remote',
    is_remote: true,
    job_type: 'Contract',
    experience_level: 'Senior',
    salary_min: 150000,
    salary_max: 190000,
    currency: 'USD',
    department: 'Mobile Engineering',
    description: '6-month contract with possibility of conversion. Help build out our next-generation crypto wallet mobile interface using React Native and TypeScript.',
    requirements: [
      '4+ years building production applications in React Native and TypeScript',
      'Experience bridging native iOS/Android modules when needed',
      'Understanding of mobile cryptography, biometrics, and secure keychain storage',
      'Solid experience with state management, animations, and offline caching'
    ],
    responsibilities: [
      'Implement responsive mobile components with 60fps gesture animations',
      'Integrate with WebSockets for real-time market order book updates',
      'Optimize app bundle size and cold-start startup time',
      'Maintain rigorous unit and end-to-end testing suites'
    ],
    skills: ['React Native', 'React', 'TypeScript', 'JavaScript', 'Mobile Development', 'GraphQL', 'REST APIs'],
    posted_at: '2026-09-02T12:00:00Z',
    apply_url: 'https://www.coinbase.com/careers',
  },
  {
    title: 'QA Automation Engineer',
    company: 'Shopify',
    logo_url: 'https://images.unsplash.com/photo-1556742049-0a67e5572293?w=128&h=128&fit=crop&crop=faces',
    location: 'Chicago, IL',
    is_remote: true,
    job_type: 'Full-time',
    experience_level: 'Mid',
    salary_min: 115000,
    salary_max: 145000,
    currency: 'USD',
    department: 'Quality Engineering',
    description: 'Design, code, and execute automated test suites for eCommerce checkout pipelines, merchant admin tools, and third-party developer APIs.',
    requirements: [
      '3+ years of software testing and automated test development experience',
      'Proficiency in TypeScript/JavaScript or Python',
      'Experience with Playwright, Cypress, Jest, and API testing tools',
      'Familiarity with CI/CD pipelines (GitHub Actions, Jenkins)'
    ],
    responsibilities: [
      'Develop end-to-end automation scripts preventing regression bugs',
      'Integrate automated tests into deployment pipelines',
      'Partner with developers to improve testability and code coverage',
      'Analyze test execution results and identify performance bottlenecks'
    ],
    skills: ['TypeScript', 'JavaScript', 'Python', 'Playwright', 'Jest', 'CI/CD', 'GitHub Actions', 'REST APIs'],
    posted_at: '2026-08-26T14:15:00Z',
    apply_url: 'https://www.shopify.com/careers',
  },
  {
    title: 'AI Research Scientist',
    company: 'Anthropic',
    logo_url: 'https://images.unsplash.com/photo-1534972195531-a756b1126f24?w=128&h=128&fit=crop&crop=faces',
    location: 'San Francisco, CA',
    is_remote: false,
    job_type: 'Full-time',
    experience_level: 'Lead',
    salary_min: 240000,
    salary_max: 330000,
    currency: 'USD',
    department: 'Research',
    description: 'Conduct foundational research on AI safety, model interpretability, and steerability of frontier neural networks.',
    requirements: [
      'PhD or equivalent research publication track record in Machine Learning or related field',
      'Extensive experience training large transformers and understanding loss landscapes',
      'Proficiency in PyTorch, JAX, or custom CUDA kernels',
      'Creative mathematical thinking and dedication to beneficial AI outcomes'
    ],
    responsibilities: [
      'Hypothesize, design, and run large-scale training experiments',
      'Analyze internal representations and mechanistic circuits of LLMs',
      'Publish research findings at conferences (NeurIPS, ICML, ICLR)',
      'Collaborate with policy and systems teams on safe deployment'
    ],
    skills: ['PyTorch', 'Python', 'Machine Learning', 'Deep Learning', 'LLMs', 'NLP', 'System Design'],
    posted_at: '2026-09-01T08:30:00Z',
    apply_url: 'https://www.anthropic.com/careers',
  },
  {
    title: 'Solutions Architect (Cloud & Enterprise)',
    company: 'Amazon Web Services (AWS)',
    logo_url: 'https://images.unsplash.com/photo-1523474255658-4af61b1614eb?w=128&h=128&fit=crop&crop=faces',
    location: 'Dallas, TX',
    is_remote: true,
    job_type: 'Full-time',
    experience_level: 'Senior',
    salary_min: 160000,
    salary_max: 210000,
    currency: 'USD',
    department: 'Solutions Architecture',
    description: 'Partner with enterprise executives and lead engineers to design resilient, cost-optimized, and secure cloud migration architectures on AWS.',
    requirements: [
      '5+ years architecting enterprise software solutions and cloud environments',
      'AWS Certified Solutions Architect Professional or equivalent expertise',
      'Strong consultative communication, presentation, and objection-handling skills',
      'Deep understanding of microservices, serverless, networking, and data storage'
    ],
    responsibilities: [
      'Guide Fortune 500 customers through cloud infrastructure designs',
      'Conduct Well-Architected Framework reviews and cost optimizations',
      'Author technical whitepapers and deliver keynote technical sessions',
      'Feed customer requirements back into AWS product engineering teams'
    ],
    skills: ['AWS', 'Cloud Architecture', 'Terraform', 'Kubernetes', 'System Design', 'Microservices', 'Docker'],
    posted_at: '2026-08-25T10:00:00Z',
    apply_url: 'https://www.amazon.jobs',
  },
  {
    title: 'Product Marketing Manager',
    company: 'HubSpot',
    logo_url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=128&h=128&fit=crop&crop=faces',
    location: 'Boston, MA',
    is_remote: true,
    job_type: 'Full-time',
    experience_level: 'Mid',
    salary_min: 120000,
    salary_max: 155000,
    currency: 'USD',
    department: 'Marketing',
    description: 'Shape the positioning, messaging, and go-to-market strategy for new CRM and marketing automation software releases.',
    requirements: [
      '3+ years in B2B SaaS product marketing or marketing management',
      'Proven ability to translate technical features into compelling customer value propositions',
      'Experience executing successful cross-channel launch campaigns',
      'Strong analytical capabilities evaluating funnel metrics and customer cohorts'
    ],
    responsibilities: [
      'Develop positioning, buyer personas, and competitive battlecards',
      'Collaborate with sales enablement on training and demo collateral',
      'Orchestrate multi-channel product launches across web, email, and social',
      'Analyze campaign ROI and optimize conversion funnels'
    ],
    skills: ['Marketing', 'Product Management', 'Data Analytics', 'Content Strategy', 'Communication', 'Agile'],
    posted_at: '2026-08-24T15:00:00Z',
    apply_url: 'https://www.hubspot.com/careers',
  },
  {
    title: 'Senior Python / Django Backend Engineer',
    company: 'Pinterest',
    logo_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=128&h=128&fit=crop&crop=faces',
    location: 'San Francisco, CA',
    is_remote: true,
    job_type: 'Full-time',
    experience_level: 'Senior',
    salary_min: 160000,
    salary_max: 205000,
    currency: 'USD',
    department: 'Engineering',
    description: 'Work on Pinterest core discovery algorithms, feed generation, and high-volume REST and GraphQL APIs serving hundreds of millions of monthly visual searches.',
    requirements: [
      '5+ years building backend web services using Python, Django, or FastAPI',
      'Extensive experience with relational databases (PostgreSQL/MySQL) and Redis caching',
      'Familiarity with event-driven pipelines and message queues',
      'Strong problem-solving and clean code architectural design skills'
    ],
    responsibilities: [
      'Design and maintain scalable Python web services',
      'Optimize database queries and indexing for sub-100ms response times',
      'Participate in architecture design reviews and sprint planning',
      'Mentor other software engineers and promote testing best practices'
    ],
    skills: ['Python', 'Django', 'FastAPI', 'PostgreSQL', 'Redis', 'REST APIs', 'GraphQL', 'Docker', 'AWS'],
    posted_at: '2026-09-02T09:00:00Z',
    apply_url: 'https://careers.pinterest.com',
  },
  {
    title: 'Frontend React Developer',
    company: 'Notion',
    logo_url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=128&h=128&fit=crop&crop=faces',
    location: 'New York, NY',
    is_remote: true,
    job_type: 'Full-time',
    experience_level: 'Mid',
    salary_min: 145000,
    salary_max: 180000,
    currency: 'USD',
    department: 'Frontend Engineering',
    description: 'Help build Notion block-based editor and database views. We care deeply about craft, typography, speed, and enabling millions of users to organize their thoughts effortlessly.',
    requirements: [
      '3+ years of intense modern React and TypeScript experience',
      'Strong understanding of rich text editing, DOM manipulation, and canvas/SVG',
      'Dedication to accessible, responsive UI with zero visual glitches',
      'Experience collaborating with world-class product designers'
    ],
    responsibilities: [
      'Build new collaborative blocks and custom view layouts',
      'Profile and optimize page load time and memory footprint',
      'Contribute reusable components to our internal design system',
      'Implement real-time sync with offline persistence'
    ],
    skills: ['React', 'TypeScript', 'JavaScript', 'HTML', 'CSS', 'Tailwind CSS', 'UI/UX Design', 'Performance'],
    posted_at: '2026-09-03T10:30:00Z',
    apply_url: 'https://www.notion.so/careers',
  },
  {
    title: 'Database Administrator & Site Reliability Engineer',
    company: 'MongoDB',
    logo_url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=128&h=128&fit=crop&crop=faces',
    location: 'Austin, TX',
    is_remote: true,
    job_type: 'Full-time',
    experience_level: 'Senior',
    salary_min: 155000,
    salary_max: 200000,
    currency: 'USD',
    department: 'Cloud Operations',
    description: 'Ensure 99.999% availability of global database clusters across public clouds. Automate backup, recovery, failover, and performance tuning.',
    requirements: [
      '5+ years administering relational or NoSQL database clusters at scale',
      'Deep knowledge of storage engines, query execution plans, and replication',
      'Proficiency in Linux system administration and infrastructure automation',
      'Experience with Terraform, Ansible, and Prometheus monitoring'
    ],
    responsibilities: [
      'Manage multi-region database topology and disaster recovery procedures',
      'Diagnose and remediate query regressions and lock contention',
      'Build automated health-checking and self-healing cloud operators',
      'Collaborate with product development teams on schema optimization'
    ],
    skills: ['MongoDB', 'PostgreSQL', 'Linux', 'Terraform', 'Kubernetes', 'Docker', 'Python', 'AWS'],
    posted_at: '2026-08-25T11:20:00Z',
    apply_url: 'https://www.mongodb.com/careers',
  }
];
